### ISSUE TITLE
unresolved external symbol .obj files

### ISSUE THREAD

**Issue by DevastMod** [CodeRedModding/CodeRed-Template#5]
edited and somehow included the sdk, but main problem is i get these errors i have no idea how to fix, on stack it seems that _some function has a declaration, but not a definition_ . no idea how to fix

![image](https://user-images.githubusercontent.com/102901194/192567514-6d8696ef-f28c-4f03-8c9b-f8363f408017.png)

**Comment by DevastMod** [comment]
if i replace sdkplaceholder with the default empty one it compiles

**Comment by ItsBranK** [comment]
The placeholder is just a placeholder, you need to use your own sdk from your game.

**Comment by ItsBranK** [comment]
There are clear requirements for using the project in the readme.md, one of them is "Moderate understanding of how Unreal Engine works (Globals, objects, actors, classes, etc)."
